<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4SLAKQP" failures="1" tests="3" name="technologyRisk.ToUpdateSelfRiskAssessmentQuestion" time="24.718" errors="0" timestamp="2023-05-04T17:40:30 IST" skipped="0">
  <testcase classname="technologyRisk.ToUpdateSelfRiskAssessmentQuestion" name="quit" time="1.108">
    <failure message="The following asserts failed:
	User is not able to delete Self RiskAssessment expected [Self RiskAssessment Deleted Successfully] but found [You cannot delete the existing Self RiskAssessment]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is not able to delete Self RiskAssessment expected [Self RiskAssessment Deleted Successfully] but found [You cannot delete the existing Self RiskAssessment]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Generic_Liberary.BaseClass.quit(BaseClass.java:187)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- quit -->
  <system-out/>
  <testcase classname="technologyRisk.ToUpdateSelfRiskAssessmentQuestion" name="delete" time="4.277"/>
  <system-out/>
  <testcase classname="technologyRisk.ToUpdateSelfRiskAssessmentQuestion" name="addNewSelfRiskAssessment" time="19.333"/>
  <system-out>
    <![CDATA[Verified Question Label in Self Assessment page
Verified Save Button in Self Assessment page
The Captured data after creating question is :16 Testing
Clicked on Edit Button
Entered a new data into question textbox
Verified save button]]>
  </system-out>
</testsuite> <!-- technologyRisk.ToUpdateSelfRiskAssessmentQuestion -->
